version: '3'
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apiqa-storage
    ports:
      - 5445:5432
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
    ports:
      - 9000:9000
