# Generated by Django 2.2 on 2019-04-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myattachfile',
            old_name='attachment_set',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='userattachfile',
            old_name='attachment_set',
            new_name='attachments',
        ),
    ]
