# Generated by Django 2.2 on 2019-05-23 16:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_storage', '0002_auto_20190423_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myattachfile',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='userattachfile',
            name='attachments',
        ),
        migrations.AddField(
            model_name='myattachfile',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Вложения'),
        ),
        migrations.AddField(
            model_name='userattachfile',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Вложения'),
        ),
    ]
