# Generated by Django 2.2 on 2019-05-30 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_storage', '0003_auto_20190523_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myattachfile',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='userattachfile',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Вложения'),
        ),
    ]
