# Generated by Django 2.2.2 on 2019-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_storage', '0005_auto_20190613_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
