# Generated by Django 2.2.2 on 2019-06-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiqa_storage', '0001_initial'),
        ('tests_storage', '0005_mymodelwithattachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelWithAttachments',
            new_name='ModelWithAttachments',
        ),
        migrations.DeleteModel(
            name='MyAttachFile',
        ),
        migrations.DeleteModel(
            name='UserAttachFile',
        ),
    ]
