# Generated by Django 3.0.5 on 2020-08-03 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests_storage', '0006_modelwithattachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelwithattachments',
            name='id',
        ),
        migrations.AddField(
            model_name='modelwithattachments',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
